{
 "title": "Flows",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "append rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(messages_appended_total[$__rate_interval])) by (pipe)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(messages_read_total[$__rate_interval])) by (pipe)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(messages_queued[5s])",
     "legendFormat": "{{pipe}}"
    }
   ]
  },
  {
   "title": "flow latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(messages_read_latency_total{pipe=\"output\"}[$__rate_interval]) / rate(messages_read_total[$__rate_interval])",
     "legendFormat": "{{origin}}"
    }
   ]
  }
 ]
}